### ISSUE TITLE
Corpora scale test fails to send slack message

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#732]
Although the test is passing if you dig into the dev scale test and the slack success webhook steps they seem to be failing 
with this error for the scale test itself
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/locust/input_events.py", line 88, in input_listener_func
    input = poller.poll()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/locust/input_events.py", line 34, in poll
    dr, dw, de = select.select([sys.stdin], [], [], 0)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/gevent/select.py", line 195, in select
    _g_sleep()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/gevent/hub.py", line 156, in sleep
    waiter.get()
  File "src/gevent/_waiter.py", line 140, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_waiter.py", line 151, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.GreenletExit
```
And the slack webhook has an `invalid_payload` error

https://github.com/chanzuckerberg/corpora-data-portal/runs/1401209817?check_suite_focus=true

**Comment by maniarathi** [comment]
Fixed: https://chanzuckerbergteam.slack.com/archives/CV7PFVABC/p1606609118051100
