### ISSUE TITLE
Adding a link when creating a new collection fails 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#861]
1.  Create a new collection.
2. `Add a Link` -> `Other `- used "https://www.chanzuckererg.com"
3. Complete the required fields and submit

No collection appears:

![Screen Shot 2021-01-27 at 1.25.52 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/0bbbfe49-d7bc-4362-8ecd-ba045450e23e)

**Comment by brianraymor** [comment]
Per @seve :

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 111, in dispatch
    flask_res = flask_app.full_dispatch_request()
  File "/var/task/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/task/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/task/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/task/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/var/task/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/var/task/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/var/task/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/var/task/chalicelib/corpora/common/utils/db_utils.py", line 123, in wrapper
    rv = func(*args, **kwargs)
  File "/var/task/chalicelib/corpora/lambdas/api/v1/collection.py", line 45, in get_collection_details
    result = collection.reshape_for_api()
  File "/var/task/chalicelib/corpora/common/entities/collection.py", line 137, in reshape_for_api
    for link in result["links"]
  File "/var/task/chalicelib/corpora/common/entities/collection.py", line 137, in <listcomp>
    for link in result["links"]
KeyError: 'link_name'
```

**Comment by Bento007** [comment]
fix by https://github.com/chanzuckerberg/corpora-data-portal/pull/876
