### ISSUE TITLE
bug: Error when logging in

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#981]
## Describe the bug
When logging in, we receive an error on the callback from auth0. This same behavior occurs in the local-dev environment.

## To Reproduce
1. Go to https://cellxgene.dev.single-cell.czi.technology/
2. make sure you are logged out
2. Click on login
3. proceed to login using one of the OIDC provider. 
3. the page will redirect to a page displaying `{"Code":"UnauthorizedError","Message":"UnauthorizedError: response from oauth server not valid"}` The URLs will looks something like this `https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/oauth2/callback?code=jM50Y3EkAVBtxSYb&state=cxlm0pqmD6j9FpPAvZdx6DoYsDgeVA`

## Environment
 - Browser chrome

## Additional context

The cause is the use of `Strict` for the sessions cookie.

**Comment by Bento007** [comment]
Here is the stack trace from the backend 
```python
corpora-api-dev - ERROR - Unable to authorize access token.
Traceback (most recent call last):
  File "/chalice/chalicelib/corpora/lambdas/api/v1/authentication.py", line 91, in oauth2_callback
    token = client.authorize_access_token()
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/flask_client/remote_app.py", line 74, in authorize_access_token
    params = self.retrieve_access_token_params(flask_req, request_token)
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/base_client/base_app.py", line 144, in retrieve_access_token_params
    params = self._retrieve_oauth2_access_token_params(request, params)
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/base_client/base_app.py", line 125, in _retrieve_oauth2_access_token_params
    raise MismatchingStateError()
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.```

**Comment by tihuan** [comment]
Can confirm that logging in via Github works in staging now 👍 Thank you!

**Comment by tihuan** [comment]
Can confirm I can log in with Github now!
